# Convert dbt docs output to an excel file
name: generate-excel-docs
on: 
  pull_request:
    branches: [main]
jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.5'
      - name: install-requirements
        run: |
          pip install -r ./python/requirements.txt
          pip install dbt==0.20.2
      # - name: create profile.yml
      #   run: python ./python/create_profile.py
      - name: dbt docs
        run: |
          python python/print_dbt_vars.py
          dbt docs generate --profiles-dir ./profiles --profile jaffle_shop
        env:
          DBT_DB_TYPE: ${{  secrets.DBT_DB_TYPE }}
          DBT_DB_ACCOUNT: ${{  secrets.DBT_DB_ACCOUNT }}
        # User/password auth
          DBT_PWD: ${{  secrets.DBT_PWD }} 
          DBT_USER: ${{  secrets.DBT_USER }} 
          DBT_ROLE: ${{  secrets.DBT_ROLE }} 
          DBT_DB: ${{  secrets.DBT_DB }} 
          DBT_WH: ${{  secrets.DBT_WH }} 
          DBT_DB_SCHEMA: ${{  secrets.DBT_DB_SCHEMA }}
      - name: generate excel docs
        run: |
          cd python
          python parse_docs.py
      - name: upload docs
        uses: actions/upload-artifact@v2
        with:
          name: Excel-dbt-docs
          path: tmp/*.xlsx
          retention-days: 7