# Test wf
name: hello-world
on: 
  pull_request:
    branches: [main]
jobs:
  hello:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Print hello
        run: |
          echo "Hello World!"
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.5'
      - name: check
        run: |
          pwd
          ls -al